readme: /README.md
repository: deptagency-dar/ideario
title: "Ideario | Innovación y Talento"
description: "Descubre idear.io, la plataforma de innovación y talento"
url: "https://deptagency-dar.github.io/ideario"
# user config
app_name: "idear.io"
email: severinidiegoignacio@gmail.com
plugins:
  - jekyll-seo-tag