readme: /README.md
repository: deptagency-dar/ideario
title: "Ideario | Innovación y Talento"
description: "Descubre ideario, la plataforma de innovación y talento"
url: "https://deptagency-dar.github.io/ideario"
# user config
app_name: "ideario"
email: diego.severini@deptagency.com
plugins:
  - jekyll-seo-tag