name: Notify on PR Merged

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get idea URL
        run: bash ./.github/workflows/get-idea-url.sh ${{ github.event.pull_request.head.sha }} ${{ secrets.GITHUB_TOKEN }}
        id: get-idea-url

      - name: Send message to Slack
        uses: rtCamp/action-slack-notify@v2.1.2
        with:
          status: ${{ job.status }}
          fields: message,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'A new idea was added to Ideario: ${{ steps.get-idea-url.outputs.idea_url }}'
          MSG_MINIMAL: true

      - name: Post a tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "A new idea was added to Ideario: ${{ steps.get-idea-url.outputs.idea_url }}"
          consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
