name: Notify Slack on PR Creation
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate PR
        run: |
          # Get the number of added files
          FILES=$(git diff --numstat origin/main...HEAD -- ideas/ | wc -l)
          
          # Check if only one file was added
          if [ "$FILES" -gt 1 ]; then
            echo "Invalid PR: Only one new file can be added under the ideas directory"
            exit 1
          fi
  notify_slack:
    runs-on: ubuntu-latest
    needs: "validate_pr"
    steps:
      # Get the download URL of the new file added
      - name: Get new file URL
        run: ./.github/workflows/get_new_file_url.sh ${{ github.event.pull_request.head.sha }} ${{ secrets.GITHUB_TOKEN }}
        id: get_new_file_url

      # Send a message to Slack with the new file content
      - name: Send message to Slack
        uses: rtCamp/action-slack-notify@v2.1.2
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName
          message: |
            New PR created: ${{ github.event.pull_request.title }}
            ```
            ${{ steps.get_new_file_content.outputs.file_content }}
            ```
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
