name: Notify Slack on PR Creation
on:
  pull_request: {}

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate PR
        run: |
          # Get the number of added files
          FILES=$(git diff --numstat origin/main...HEAD -- ideas/ | wc -l)
          echo $FILES
          # Check if only one file was added
          if [ "$FILES" -gt 1 ]; then
            echo "Invalid PR: Only one new file can be added under the ideas directory"
            exit 1
          fi
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Get the download URL of the new file added
      - name: Get new file URL
        run: bash ./.github/workflows/get-new-file-url.sh ${{ github.event.pull_request.head.sha }} ${{ secrets.GITHUB_TOKEN }}
        id: get-new-file-url

      # Send a message to Slack with the new file content
      - name: Send message to Slack
        uses: rtCamp/action-slack-notify@v2.1.2
        with:
          status: ${{ job.status }}
          fields: message,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
          SLACK_MESSAGE: ${{ steps.get-new-file-url.outputs.file_content }}
          MSG_MINIMAL: true
  get_chatgpt_feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Get ChatGPT feedback
        run: bash ./scripts/ask_chat_gpt.sh
        id: get-chatgpt-feedback
      - name: Send message to Slack
        uses: rtCamp/action-slack-notify@v2.1.2
        with:
          status: ${{ job.status }}
          fields: message,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_MESSAGE: ${{ steps.get-chatgpt-feedback.outputs.chatgpt_feedback }}
          MSG_MINIMAL: true